using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections.Specialized;

namespace tMod_v3
{
    [Serializable]
    public class Configuration
    {
        public bool AsyncMod = true;
        public string BindAddress = "0.0.0.0";
        public int BindPort = 7777;
        public int PlayerSlots = 100;
        public bool CheckForUpdates = true;
        public string WorldPath = "world1.wld";
        public string Database = @"%CD%\tMod\Database.sdf";
        public string ServerPassword = "";
        public string MOTD = "Welcome to a tMod powered server!";
        public bool RequireAlphaNumericName = true;
        public bool RequireHardcoreCharacter = false;
        public bool EnableRollbackTrimming = true;
        public bool AutomaticallyTrimRollbacks = false;
        public int MaximumRollbackEntries = 10000000;
        public bool AllowMassDestruction = false;
        public bool KickMassDestruction = false;
        public bool BanMassDestruction = false;
        public int MassDestructionSensitivity = 20;
        public bool AllowMassConstruction = false;
        public bool KickMassConstruction = false;
        public bool BanMassConstruction = false;
        public int MassConstructionSensitivity = 5;
        public bool UseBuiltInAntiSpam = true;
        public bool AllowExplosives = false;
        public bool KickExplosives = true;
        public bool AllowConstruction = true;
        public bool AllowDestruction = true;
        public bool AllowLava = true;
        public bool AllowWater = true;
        public bool AllowSpikes = true;
        public bool AllowSpawnNpcs = false;
        public bool AllowChest = true;
        public bool AllowSignEditing = true;
        public bool AllowPlayerItemDropping = true;
        public bool KickHealthHack = true;
        public bool KickManaHack = true;
        public bool KickItemStackHack = true;
        public bool KickDamageHack = true;
        public bool KickSpawnNpc = true;
        public bool KickInvalidTileEdits = true;
        public bool KickLiquidHack = true;
        public bool KickSendTileSquareHack = true;
        //public bool KickTeleportHack = false;
        //public bool KickSpeedHack = false;
        //public bool KickNoClipHack = false;
        //public bool KickMiscHack = false;
        //public bool KickAvatarHack = false;
        //public bool KickRangeHack = false;
        //public bool DisallowTModClientCheating = false;
        public bool BlockRegistration = false;
        public bool RequireRegistration = false;
        public bool RequireRegistrationForChat = false;
        public bool RequireRegistrationForDoors = false;
        //public bool RequireNewCharacterAlways = false;
        public bool Peaceful = false;
        //public bool InfiniteInvasion = false;
        public bool AdvertEnabled = true;
        //public int ServerTime = -1;
        //public bool FreezeTime = false;
        public int MaximumSpawns = 4;
        public int SpawnRate = 700;
        public string PluginDirectory = @"tMod\Plugins";
        public string PluginDataDirectory = @"tMod\Plugins\Data";
        public StringCollection Plugins = new StringCollection();
        public StringCollection Ops = new StringCollection();
        public StringCollection Mods = new StringCollection();
        public StringCollection AlternativePasswords = new StringCollection();
        public bool ShowKickNotifications = true;
        public bool ShowBanNotifications = true;
        public bool AllowRegistrationPasswordForServerPassword = false;
        public dynamic RequireNewCharacterIfNotRegistered = false;
        public dynamic RequireNewCharacterAlways = false;
        public bool ShowNPCNotifications = true;
        public int SpawnProtectionRadius = 0;
        public bool KickAvatarRenameHack = true;
        public bool KickImpersonatingName = true;
        public bool KickInvalidName = true;
        public bool KickSpikeHack = true;
        public string OpMePassword = "Disabled";
        public bool ForceChatColors = true;
        public bool ColorOpChat = true;
        public bool ColorModChat = true;
        public Rgb OpColor = new Rgb(175, 75, 0xff);
        public Rgb ModColor = new Rgb(25, 175, 0);
        public Rgb MemberColor = new Rgb(0xff);
        public Rgb GuestColor = new Rgb(0xbb);
        public bool AllowAbove150Damage = false;
        public bool ShowOpMeNotifications = true;
        public bool BlockSendTileSquare = true;
        public bool BlockRangeHack = true;
    }
}
